Repository gardener/gardener-extension-provider-azure, pull requests merged in 2020-10, with the labels that each got.

#173 Enhance chart options
  Dockerfile
  charts/gardener-extension-provider-azure/templates/deployment.yaml
  charts/gardener-extension-provider-azure/templates/vpa.yaml
  charts/gardener-extension-provider-azure/values.yaml
  example/controller-registration.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#174 Add k8s 1.19 conformance tests (testgrid) links
  README.md
Labels: kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#176 Update enduser docs
  docs/usage-as-end-user.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#177 Vendor gardener/gardener@v1.11.1 without a hack
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#179 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: needs/ok-to-test, size/xs

#181 add priority class for extension pods
  charts/gardener-extension-provider-azure/templates/_helpers.tpl
  charts/gardener-extension-provider-azure/templates/deployment.yaml
  charts/gardener-extension-provider-azure/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#180 A bit boy scout for the controlplane/valuesprovider tests
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xl

#183 Do no longer ignore deprecated item usage
  .golangci.yaml
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs
