Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-05, with the labels that each got.

#292 Configure TCP egress for shoots
  charts/internal/shoot-system-components/charts/allow-egress/Chart.yaml
  charts/internal/shoot-system-components/charts/allow-egress/templates/allow-tcp-egress.yaml
  charts/internal/shoot-system-components/charts/allow-egress/templates/allow-udp-egress.yaml
  charts/internal/shoot-system-components/requirements.yaml
  charts/internal/shoot-system-components/values.yaml
  pkg/azure/types.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/azure, reviewed/lgtm, size/s

#297 Prepare PATH in prepare_release in advance
  .ci/prepare_release
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#299 Fix volume fsType handling for CSI volumes
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/_deployment.tpl
Labels: area/storage, kind/bug, needs/ok-to-test, needs/review, platform/azure, size/xs

#300 Fix the ./.ci/prepare_release script
  .ci/prepare_release
  hack/.ci/prepare_release
Labels: kind/bug, needs/ok-to-test, needs/review, size/s

#302 Keep the volumesnapshotclasses CRD on ControlPlane deletion
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
Labels: kind/bug, needs/ok-to-test, needs/review, platform/azure, size/xs

#301 Add validation for cloud provider Secrets
  charts/gardener-extension-admission-azure/charts/application/templates/validatingwebhook-validator.yaml
  cmd/gardener-extension-admission-azure/app/app.go
  docs/local-setup.md
  example/40-validatingwebhookconfiguration.yaml
  hack/dev-setup-admission-azure.sh
  pkg/admission/cmd/options.go
  pkg/admission/validator/secret.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/azure/validation/secrets.go
  pkg/apis/azure/validation/secrets_test.go
  pkg/internal/infrastructure/infrastructure.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/index/index.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/secret.go
  vendor/modules.txt
Labels: area/ops-productivity, area/robustness, kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/l

#295 Use Go templates for terraform
  charts/internal/azure-infra/Chart.yaml
  charts/internal/azure-infra/templates/_helpers.tpl
  charts/internal/azure-infra/values.yaml
  go.mod
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/internal/infrastructure/template.go
  pkg/internal/infrastructure/templates/main.tpl.tf
  pkg/internal/infrastructure/templates/terraform.tfvars
  pkg/internal/infrastructure/templates/variables.tf
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  vendor/modules.txt
Labels: area/control-plane, kind/cleanup, kind/test, merge/squash, needs/ok-to-test, platform/azure, reviewed/do-not-merge, reviewed/lgtm, size/l

#305 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#309 [release-v1.20] Prepare next Dev Cycle v1.20.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/delivery, kind/bug, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#310 [release-v1.20] Automated cherry pick of #307: [ci:component:github.com/gardener/machine-controller-manager-provider-azure:v0.3.3->v0.4.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#311 [release-v1.20] Automated cherry pick of #306: [ci:component:github.com/gardener/machine-controller-manager:v0.38.0->v0.39.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#313 [release-v1.20] Automated cherry pick of #312: [ci:component:github.com/gardener/machine-controller-manager-provider-azure:v0.4.0->v0.4.1]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#314 Vendor gardener/gardener@v1.23.0
  go.mod
  go.sum
  pkg/controller/controlplane/valuesprovider.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/shoot.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/control_plane.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#308 Do not ensure apiserver flag `external-hostname`
  pkg/webhook/controlplaneexposure/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#315 Vendor gardener/gardener@v1.23.1
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#317 Update the admission-azure RBAC after cloud provider Secrets validation feature
  charts/gardener-extension-admission-azure/charts/application/templates/rbac.yaml
Labels: kind/bug, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#316 Expose logs from user exposed components in the new way
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs
