Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-04, with the labels that each got.

#273 Vendor gardener/gardener@v1.19.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/noopvaluesprovider.go
  vendor/github.com/gardener/gardener/hack/.ci/component_descriptor
  vendor/github.com/gardener/gardener/pkg/apis/core/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_common.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#275 Update kubernetes-csi/external-snapshotter
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#278 depend on publish-trait, rather on injected step(s)
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#276 Fix vmo cluster deletion if the worker status is empty
  pkg/controller/worker/machines.go
  pkg/controller/worker/machineset_vmo.go
Labels: kind/bug, needs/ok-to-test, platform/azure, reviewed/lgtm, size/m

#283 [release-v1.19] Fix vmo deletion if the worker status is empty
  pkg/controller/worker/machines.go
  pkg/controller/worker/machineset_vmo.go
Labels: kind/bug, needs/ok-to-test, needs/review, platform/azure, size/m

#281 Switch to kaniko oci builder
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#257 Changes needed for MCM OOT for Azure
  charts/gardener-extension-provider-azure/templates/configmap-logging.yaml
  charts/images.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  charts/internal/machineclass/templates/machineclass.yaml
  example/controller-registration.yaml
  pkg/azure/types.go
  pkg/controller/worker/machine_controller_manager.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/dev-productivity, kind/api-change, merge/squash, needs/ok-to-test, platform/azure, priority/4, reviewed/do-not-merge, reviewed/lgtm, size/m

#277 Specify container resources for CSI sidecars
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/_daemonset.tpl
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#287 Decrease terraformer log level
  pkg/internal/terraform.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm, size/xs
