Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-07, with the labels that each got.

#327 Update kubernetes-sigs/azuredisk-csi-driver
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#330 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#332 Fix dynamic provisioning with the etcd StorageClass on Kubernetes v1.21
  charts/gardener-extension-provider-azure/templates/storageclass.yaml
  example/controller-registration.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#334 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-provider-azure/templates/deployment.yaml
  charts/gardener-extension-provider-azure/values.yaml
  cmd/gardener-extension-provider-azure/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#333 [release-v1.20] Automated cherry pick of #332: Fix dynamic provisioning with the etcd StorageClass on Kubernetes v1.21
  charts/gardener-extension-provider-azure/templates/storageclass.yaml
  example/controller-registration.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#324 Update kubernetes-csi/external-snapshotter to v3.0.3
  charts/images.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
Labels: area/storage, kind/enhancement, lifecycle/stale, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xl

#343 Set minAllowed memory for csi-driver-node-{disk,file} containers
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/_vpa.tpl
Labels: area/storage, kind/bug, needs/ok-to-test, needs/review, platform/azure, reviewed/lgtm, size/xs

#339 Updated MCM RBACs to support VolumeAttachments
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/dev-productivity, kind/api-change, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#342 Clean up handling for unsupported K8s versions
  README.md
  charts/gardener-extension-provider-azure/templates/_helpers.tpl
  charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl
  charts/internal/cloud-provider-config/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/_helpers.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller.yaml
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/webhook/controlplaneexposure/ensurer.go
Labels: kind/cleanup, needs/ok-to-test, platform/azure, reviewed/lgtm, size/s

#344 Increased PV reattachment timeout to 150s
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#348 Vendor g/g@v1.27.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/.ci/prepare_release
  vendor/github.com/gardener/gardener/hack/test-cover-clean.sh
  vendor/github.com/gardener/gardener/hack/test-cover.sh
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/hack/test-prometheus.sh
  vendor/github.com/gardener/gardener/hack/test.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  vendor/modules.txt
Labels: kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#346 Add release milestone check action
  .github/workflows/release-milestone.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#350 Fix: Allow remedy-controller to create,read,list,watch leases
  charts/internal/seed-controlplane/charts/remedy-controller-azure/templates/role.yaml
Labels: kind/cleanup, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#349 Fix integration testing leaked resourcegroups
  test/integration/infrastructure/infrastructure_test.go
  test/integration/infrastructure/matchers.go
Labels: area/testing, kind/bug, kind/test, needs/ok-to-test, platform/azure, reviewed/lgtm, reviewed/ok-to-test, size/s
