Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-02, with the labels that each got.

#243 Ensure the StorageAccount has MinimumTLSVersion set to TLS12
  pkg/azure/client/storageaccount.go
Labels: area/backup, area/security, kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xs

#245 validation refactor and cloudprofile validation
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  charts/gardener-extension-admission-azure/.helmignore
  charts/gardener-extension-admission-azure/Chart.yaml
  charts/gardener-extension-admission-azure/charts/application/Chart.yaml
  charts/gardener-extension-admission-azure/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-azure/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-azure/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-azure/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-azure/charts/application/values.yaml
  charts/gardener-extension-admission-azure/charts/runtime/Chart.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-admission-azure/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/secret-cert.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-azure/charts/runtime/values.yaml
  charts/gardener-extension-admission-azure/templates/_helpers.tpl
  charts/gardener-extension-admission-azure/values.yaml
  charts/gardener-extension-validator-azure/Chart.yaml
  charts/gardener-extension-validator-azure/charts/application/Chart.yaml
  charts/gardener-extension-validator-azure/charts/runtime/Chart.yaml
  cmd/gardener-extension-admission-azure/app/app.go
  cmd/gardener-extension-admission-azure/main.go
  example/40-validatingwebhookconfiguration.yaml
  example/admission-azure-certs/tls.crt
  example/admission-azure-certs/tls.key
  pkg/admission/cmd/options.go
  pkg/admission/validator/cloudprofile.go
  pkg/admission/validator/serialization.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/azure/validation/cloudprofile.go
  pkg/apis/azure/validation/cloudprofile_test.go
  pkg/validator/shoot_handler.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/xl

#247 Clean up the stale target build stage
  Dockerfile
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#248 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#250 Vendor gardener/gardener@v1.16.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#249 [release-v1.18] Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#251 [release-v1.18] Vendor gardener/gardener@v1.16.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#246 VPA for validator/admission component
  charts/gardener-extension-admission-azure/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-azure/values.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, needs/ok-to-test, platform/azure, priority/normal, reviewed/lgtm, size/s

#254 Update kubernetes-csi/external-snapshotter to v2.1.4
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
