Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-11, with the labels that each got.

#390 Add Kubernetes v1.22 conformance badge
  README.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#395 Add docforge manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/azure

#399 Improve the error message when a required part of webhookConfig is missing
  charts/gardener-extension-admission-azure/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-azure/charts/runtime/templates/secret-cert.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#398 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#402 Updated cluster creation tutorial
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/_index.md
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/azuregetclientid.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/azuregettenantid.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/azureselectspn.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/azureselectsubscription.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/gardeneraddazuresecret.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/gardenernewazuresecret.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/new_cluster.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/new_gardener_project.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/plus_icon.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/request_spn.jpg
  docs/tutorials/kubernetes-cluster-in-azure-with-gardener/images/request_spn1.jpg
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/_index.md
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/add-azure-secret.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/azure-choose-subscription.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/azure-select-subscription.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/copy-kubeconfig.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/create-cluster.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/create-secret-azure.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/new-cluster.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/new-gardener-project.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/plus-icon.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/processing-cluster.png
  docs/tutorials/kubernetes-cluster-on-azure-with-gardener/images/secret-stored.png
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, platform/azure, merge/squash

#405 Update remedy-controller to v0.9.0
  charts/images.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure
