Repository gardener/gardener-extension-provider-azure, pull requests merged in 2021-08, with the labels that each got.

#347 Expose MCM logs to the end-users
  charts/gardener-extension-provider-azure/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/xs

#352 Stop using `github.com/pkg/errors`
  go.mod
  pkg/apis/azure/helper/scheme.go
  pkg/controller/controlplane/actuator.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/worker/helper.go
  pkg/controller/worker/machine_images.go
  pkg/controller/worker/machines.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer.go
  test/tm/generator.go
  vendor/modules.txt
Labels: kind/enhancement, needs/ok-to-test, platform/azure, reviewed/lgtm, size/s

#354 Upgrade github.com/gardener/cloud-provider-azure@v1.21
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#355 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#357 [release-v1.21] Automated cherry pick of #355: Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#356 Upgrade github.com/gardener/cloud-provider-azure
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#358 Update VMSS Flex/VMO documentation
  docs/usage-as-end-user.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#361 Reintroduce generation of tf config on deletion
  pkg/controller/infrastructure/actuator_delete.go
Labels: kind/regression, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#367 Add Kubernetes v1.21 conformance badge
  README.md
Labels: needs/ok-to-test

#363 Fix worker vmo deletion if resource group is gone
  pkg/azure/client/vmss.go
  pkg/controller/worker/machine_dependencies_test.go
  pkg/controller/worker/machineset_vmo.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure
