Repository gardener/gardener-extension-provider-azure, pull requests merged in 2023-09, with the labels that each got.

#727 Bump k8s.io/client-go to v0.26.4
  go.mod
  go.sum
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, platform/azure

#728 Bump k8s.io/client-go to v0.26.4 (#727)
  go.mod
  go.sum
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#729 Update v1.27 conformance test coverage
  README.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure
