Repository gardener/gardener-extension-provider-azure, pull requests merged in 2023-04, with the labels that each got.

#658 Update azuredisk to latest
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#657 Make the `gardener-extension-admission-azure` Service topology-aware
  charts/gardener-extension-admission-azure/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-azure/values.yaml
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#659 declare resource-id from resources from remote component
  charts/images.yaml
Labels: area/delivery, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#661 Handle user related error code at missing place in infra deletion flow
  pkg/controller/infrastructure/actuator_delete.go
Labels: area/ops-productivity, kind/regression, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#666 Port prepare removal of component cli to v1.34
  charts/images.yaml
Labels: area/delivery, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#671 allow rg deletion with other resources
  pkg/internal/infrastructure/templates/main.tpl.tf
Labels: area/control-plane, kind/regression, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#675 prepare next dev cycle v1.35.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/control-plane, kind/regression, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#674 Remove out-of-support flags from deployment Yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/usability, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#676 [release-v1.35] Automated cherry pick of #671: allow rg deletion with other resources
  pkg/internal/infrastructure/templates/main.tpl.tf
Labels: area/control-plane, kind/regression, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#669 Prevent shoot clusters with calico from configuring overlay network, which is not supported on azure
  pkg/admission/validator/shoot.go
  pkg/apis/azure/validation/shoot.go
  pkg/apis/azure/validation/shoot_test.go
Labels: area/networking, area/usability, kind/bug, needs/ok-to-test, needs/changes, needs/review, reviewed/lgtm, size/m, platform/azure
