Repository gardener/gardener-extension-provider-azure, pull requests merged in 2023-12, with the labels that each got.

#751 Add new mutator tests to clarify expected behavior.
  pkg/admission/mutator/shoot_test.go
Labels: area/networking, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#758 Update testmachinery image location
  .ci/pipeline_definitions
Labels: area/delivery, kind/task, needs/ok-to-test, needs/review, reviewed/lgtm, size/xs, platform/azure

#760 Update azurecsi-file images
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/azure

#763 Vendor gardener/gardener@v1.83.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/github.com/gardener/gardener/hack/kind-up.sh
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/control-plane-migration, platform/azure

#762 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  charts/gardener-extension-admission-azure/values.yaml
  charts/gardener-extension-provider-azure/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#765 add delete-on-invalid-update on CSIDriver objects
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/csidriver-disk.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/csidriver-file.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/azure

#767 Add Kubernetes v1.28 conformance test badge
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#768 increase release integration test timeout
  .ci/test-integration.sh
Labels: kind/test, needs/ok-to-test, needs/review, size/xs, platform/azure, area/testing
