Repository gardener/gardener-extension-provider-azure, pull requests merged in 2024-01, with the labels that each got.

#770 Set COMPONENT_PREFIXES env variable to fix upgrade PRs
  .ci/component_descriptor
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#773 Cherry-pick of #772
  imagevector/images.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#778 Update azure-csi images
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#779 update image rules
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#780 Fix hook-me script
  Makefile
  hack/dev-setup-admission-azure.sh
  hack/hook-me.sh
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, status/closed, platform/azure

#783 deprecate mcm charts
  charts/gardener-extension-provider-azure/templates/clusterfilters-logging.yaml
  charts/internal/machine-controller-manager/seed/Chart.yaml
  charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  charts/internal/machine-controller-manager/seed/templates/clusterrolebinding.yaml
  charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/Chart.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/azure/types.go
  pkg/webhook/controlplane/add.go
  test/integration/healthcheck/test.go
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl, platform/azure

#784 Vendor gardener/gardener@v1.87.1
  .ci/hack/component_descriptor
  go.mod
  go.sum
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, platform/azure
