Repository gardener/gardener-extension-provider-azure, pull requests merged in 2024-07, with the labels that each got.

#908 Fix infra mutator
  pkg/webhook/infrastructure/add.go
  pkg/webhook/infrastructure/flow.go
  pkg/webhook/infrastructure/flow_test.go
  pkg/webhook/infrastructure/infrastructure.go
  pkg/webhook/infrastructure/layout.go
  pkg/webhook/infrastructure/layout_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, platform/azure

#911 Cherry-pick PR#908 to release-branch v1.45
  pkg/webhook/infrastructure/add.go
  pkg/webhook/infrastructure/flow.go
  pkg/webhook/infrastructure/flow_test.go
  pkg/webhook/infrastructure/infrastructure.go
  pkg/webhook/infrastructure/layout.go
  pkg/webhook/infrastructure/layout_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#912 rm failing preStop hook
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.tpl
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#916 Update k8s v1.30 conformance test coverage
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/azure

#875 Detect Cloud Instance by Region as Fallback
  charts/internal/machineclass/templates/machineclass.yaml
  pkg/apis/azure/types_cloudprofile.go
  pkg/azure/client/client_opts.go
  pkg/azure/client/helper.go
  pkg/controller/backupbucket/actuator.go
  pkg/controller/bastion/actuator_delete.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/dnsrecord/actuator.go
  pkg/controller/dnsrecord/actuator_test.go
  pkg/controller/infrastructure/flow_reconciler.go
  pkg/controller/infrastructure/terraform_reconciler.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, platform/azure

#913 [admission] Add `priorityClassName`
  charts/gardener-extension-admission-azure/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-azure/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#920 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, size/s, platform/azure

#906 Extend diagnostic profile usage example
  docs/usage/usage.md
  example/30-worker.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/azure

#925 Make infra-flow deletion more resilient
  pkg/controller/infrastructure/infraflow/ensurer.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#924 Inserts Architecture from worker to machineclass
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/azure

#929 fix an issue where shoots would be migrated to flow during cp-migration
  pkg/webhook/infrastructure/flow.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/azure

#930 [release 1.45] fix an issue where shoots would be migrated to flow during cp-migration
  pkg/webhook/infrastructure/flow.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure
