Repository gardener/gardener-extension-provider-azure, pull requests merged in 2025-07, with the labels that each got.

#1218 Fix missing rbac for CSI controller disk
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-driver-controller-disk.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure

#1225 migrate CICD-Pipeline to GitHub-Actions
  .ci/component_descriptor
  .ci/pipeline_definitions
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .github/workflows/run-integrationtests.yaml
  .github/workflows/upgrade-dependencies.yaml
  .ocm/base-component.yaml
Labels: area/delivery, kind/technical-debt, kind/task, needs/ok-to-test, needs/review, needs/second-opinion, size/l, platform/azure

#1230 update gha for new release options
  .github/workflows/build.yaml
  .github/workflows/release.yaml
Labels: area/delivery, kind/enhancement, needs/review, reviewed/ok-to-test, size/xs, platform/azure

#1234 update ocm name
  .ocm/base-component.yaml
Labels: area/delivery, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/azure
